---
# sync data from Azure Production --> local yaml files
providers:
  azure-qa:
    class: octodns_azure.AzurePrivateProvider
    client_id: env/AZURE_QA_CLIENT_ID
    directory_id: env/AZURE_QA_DIRECTORY_ID
    key: env/AZURE_QA_AUTHENTICATION_KEY
    resource_group: Q9011ADCO-CC-PvDNS-RG01
    sub_id: env/AZURE_QA_SUBSCRIPTION_ID
  local-azure-qa:
    class: octodns.provider.yaml.YamlProvider
    directory: ./azure-qa-zones
    enforce_order: true
  azure-prod:
    class: octodns_azure.AzurePrivateProvider
    client_id: env/AZURE_PRD_CLIENT_ID
    directory_id: env/AZURE_PRD_DIRECTORY_ID
    key: env/AZURE_PRD_AUTHENTICATION_KEY
    resource_group: P9011ADCO-CC-PvDNS-RG01
    sub_id: env/AZURE_PRD_SUBSCRIPTION_ID
  local-azure-prod:
    class: octodns.provider.yaml.YamlProvider
    directory: ./azure-prod-zones
    enforce_order: true

zones:
  # This is a dynamic zone config. The source(s), here `config`, will be
  # queried for a list of zone names and each will dynamically be set up to
  # match the dynamic entry.
  '*':
    sources:
      - azure-prod
    targets:
      - local-azure-prod
