providers:
  bluecat:
    class: octodns_bluecat.BlueCatProvider
    endpoint: env/BAM_ENDPOINT
    username: env/BAM_USER
    password: env/BAM_PW
    token: env/BAM_TOKEN
    confname: env/BAM_CONF
    viewname: env/BAM_VIEW
  powerdns:
    class: octodns_powerdns.PowerDnsProvider
    host: mirror.eis.utoronto.ca
    port: 8081
    api_key: env/POWERDNS_API_KEY
    scheme: http

processors:
  only-a-and-aaaa:
    class: octodns.processor.filter.TypeAllowlistFilter
    allowlist:
      - A
      - AAAA
  no-root-ns:
    class: octodns.processor.filter.IgnoreRootNsFilter

zones:
  '*':
    sources:
      - bluecat
    processors:
      - only-a-and-aaaa
    targets:
      - powerdns
