providers:
  bluecat-v1:
    class: octodns_bluecat_v1.BlueCatProvider
    endpoint: env/BAM_ENDPOINT
    username: env/BAM_USER
    password: env/BAM_PW
    token: env/BAM_TOKEN
    confname: env/BAM_CONF
    viewname: env/BAM_VIEW
  yaml:
    class: octodns.provider.yaml.YamlProvider
    directory: ./leaf-zones
    default_ttl: 3600
    enforce_order: True

processors:
  only-a-and-aaaa:
    class: octodns.processor.filter.TypeAllowlistFilter
    allowlist:
      - A
      - AAAA
  no-root-ns:
    class: octodns.processor.filter.IgnoreRootNsFilter

zones:
  '*':
    sources:
      - bluecat-v1
    processors:
      - only-a-and-aaaa
    targets:
      - yaml
