---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    default_ttl: 3600
    enforce_order: True
  azure:
    class: octodns_azure.AzurePrivateProvider
    client_id: env/AZURE_APPLICATION_ID
    key: env/AZURE_AUTHENTICATION_KEY
    directory_id: env/AZURE_DIRECTORY_ID
    sub_id: env/AZURE_SUBSCRIPTION_ID
    resource_group: Q9011ADCO-CC-PvDNS-RG01

zones:
  # This is a dynamic zone config. The source(s), here `config`, will be
  # queried for a list of zone names and each will dynamically be set up to
  # match the dynamic entry.
  '*':
    sources:
      - config
    targets:
      - azure
