---
providers:
  azure-qa:
    class: octodns_azure.AzurePrivateProvider
    client_id: env/AZURE_QA_CLIENT_ID
    directory_id: env/AZURE_QA_DIRECTORY_ID
    key: env/AZURE_QA_AUTHENTICATION_KEY
    resource_group: Q9011ADCO-CC-PvDNS-RG01
    sub_id: env/AZURE_QA_SUBSCRIPTION_ID
  config-qa:
    class: octodns.provider.yaml.YamlProvider
    default_ttl: 3600
    directory: ./qa-zones
    enforce_order: true
  config-merged:
    class: octodns.provider.yaml.YamlProvider
    default_ttl: 3600
    directory: ./merged-zones
    enforce_order: true

processors:
  only_a_cname_rrs:
    class: octodns.processor.filter.TypeAllowlistFilter
    allowlist:
      - A
      - AAAA
      - CNAME
  qa_hnames_only:
    class: octodns.processor.filter.NameAllowlistFilter
    allowlist:
      - /^q\d{3}[_-a-z]*/
  qa_addrs_only:
    class: octodns.processor.filter.NetworkValueAllowlistFilter
    allowlist:
      - 10.141.0.0/16

zones:
  # This is a dynamic zone config. The source(s), here `config`, will be
  # queried for a list of zone names and each will dynamically be set up to
  # match the dynamic entry.
  '*':
    sources:
      - config-merged
    processors:
      - only_a_cname_rrs
      - qa_hnames_only
      - qa_addrs_only
    targets:
      - azure-qa

