---
providers:
  azure-prod:
    class: octodns_azure.AzurePrivateProvider
    client_id: env/AZURE_PRD_CLIENT_ID
    directory_id: env/AZURE_PRD_DIRECTORY_ID
    key: env/AZURE_PRD_AUTHENTICATION_KEY
    resource_group: P9011ADCO-CC-PvDNS-RG01
    sub_id: env/AZURE_PRD_SUBSCRIPTION_ID
  config-prod:
    class: octodns.provider.yaml.YamlProvider
    default_ttl: 3600
    directory: ./prod-zones
    enforce_order: true

processors:
  only-a-aaaa-rrs:
    class: octodns.processor.filter.TypeAllowlistFilter
    allowlist:
      - A
      - AAAA
  no-root-ns:
    class: octodns.processor.filter.IgnoreRootNsFilter

zones:
  # This is a dynamic zone config. The source(s), here `config`, will be
  # queried for a list of zone names and each will dynamically be set up to
  # match the dynamic entry.
  '*':
    sources:
      - config-prod
    processors:
      - only-a-aaaa-rrs
      - no-root-ns
    targets:
      - azure-prod
