---
manager:
  include_meta: True
  max_workers: 2

providers:
  axfr:
    class: octodns_bind.AxfrSource
    host: 128.100.103.119
    port: 53
    ipv6: false
    timeout: 15
  azure:
    class: octodns_azure.AzurePrivateProvider
    client_id: env/AZURE_APPLICATION_ID
    key: env/AZURE_AUTHENTICATION_KEY
    directory_id: env/AZURE_DIRECTORY_ID
    sub_id: env/AZURE_SUBSCRIPTION_ID
    resource_group: Q9011ADCO-CC-PvDNS-RG01
  local:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    default_ttl: 3600
    enforce_order: True
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN

zones:
  privatelink.adf.azure.com.:
    sources:
      - azure
    targets:
      - local
