providers:
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
      #    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN
      #    account_id: env/CLOUDFLARE_ACCOUNT_ID
  yaml:
    class: octodns.provider.yaml.YamlProvider
    directory: ./cf-zones
    default_ttl: 3600
    enforce_order: True

zones:
  278.privatelink.postgres.database.azure.com.:
    sources:
      - yaml
    targets:
      - cloudflare
